// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf C++ Version: 7.34.1

#include "inference.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace inference {

inline constexpr InferenceResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        embedding_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::inference::InferenceResponse,
            PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.embedding_)>()
        }
        #else
        embedding_ {}
        #endif
        ,
        is_stale_{false},
        x_{0},
        y_{0},
        z_{0} {}

template <typename>
constexpr InferenceResponse::InferenceResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(InferenceResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct InferenceResponseDefaultTypeInternal {
  constexpr InferenceResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InferenceResponseDefaultTypeInternal() {}
  union {
    InferenceResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InferenceResponseDefaultTypeInternal _InferenceResponse_default_instance_;

inline constexpr InferenceRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        log_line_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        model_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr InferenceRequest::InferenceRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(InferenceRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct InferenceRequestDefaultTypeInternal {
  constexpr InferenceRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InferenceRequestDefaultTypeInternal() {}
  union {
    InferenceRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InferenceRequestDefaultTypeInternal _InferenceRequest_default_instance_;
}  // namespace inference
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_inference_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_inference_2eproto = nullptr;
const ::uint32_t
    TableStruct_inference_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::inference::InferenceRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::inference::InferenceRequest, _impl_.log_line_),
        PROTOBUF_FIELD_OFFSET(::inference::InferenceRequest, _impl_.model_id_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.embedding_),
        PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.is_stale_),
        PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.z_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::inference::InferenceRequest)},
        {7, sizeof(::inference::InferenceResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::inference::_InferenceRequest_default_instance_._instance,
    &::inference::_InferenceResponse_default_instance_._instance,
};
const char descriptor_table_protodef_inference_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017inference.proto\022\tinference\"6\n\020Inferenc"
    "eRequest\022\020\n\010log_line\030\001 \001(\t\022\020\n\010model_id\030\002"
    " \001(\t\"Y\n\021InferenceResponse\022\021\n\tembedding\030\001"
    " \003(\002\022\020\n\010is_stale\030\003 \001(\010\022\t\n\001x\030\004 \001(\002\022\t\n\001y\030\005"
    " \001(\002\022\t\n\001z\030\006 \001(\0022\\\n\017InferenceEngine\022I\n\014Ru"
    "nInference\022\033.inference.InferenceRequest\032"
    "\034.inference.InferenceResponseB\tZ\007./proto"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_inference_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_inference_2eproto = {
    false,
    false,
    288,
    descriptor_table_protodef_inference_2eproto,
    "inference.proto",
    &descriptor_table_inference_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_inference_2eproto::offsets,
    file_level_enum_descriptors_inference_2eproto,
    file_level_service_descriptors_inference_2eproto,
};
namespace inference {
// ===================================================================

class InferenceRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<InferenceRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_._has_bits_);
};

InferenceRequest::InferenceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InferenceRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:inference.InferenceRequest)
}
PROTOBUF_NDEBUG_INLINE InferenceRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::inference::InferenceRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        log_line_(arena, from.log_line_),
        model_id_(arena, from.model_id_) {}

InferenceRequest::InferenceRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const InferenceRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InferenceRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InferenceRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:inference.InferenceRequest)
}
PROTOBUF_NDEBUG_INLINE InferenceRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        log_line_(arena),
        model_id_(arena) {}

inline void InferenceRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
InferenceRequest::~InferenceRequest() {
  // @@protoc_insertion_point(destructor:inference.InferenceRequest)
  SharedDtor(*this);
}
inline void InferenceRequest::SharedDtor(MessageLite& self) {
  InferenceRequest& this_ = static_cast<InferenceRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.log_line_.Destroy();
  this_._impl_.model_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL InferenceRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) InferenceRequest(arena);
}
constexpr auto InferenceRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(InferenceRequest),
                                            alignof(InferenceRequest));
}
constexpr auto InferenceRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_InferenceRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &InferenceRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<InferenceRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &InferenceRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<InferenceRequest>(), &InferenceRequest::ByteSizeLong,
              &InferenceRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_._cached_size_),
          false,
      },
      &InferenceRequest::kDescriptorMethods,
      &descriptor_table_inference_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull InferenceRequest_class_data_ =
        InferenceRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
InferenceRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&InferenceRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(InferenceRequest_class_data_.tc_table);
  return InferenceRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 51, 2>
InferenceRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    InferenceRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::inference::InferenceRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string model_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_.model_id_)}},
    // string log_line = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_.log_line_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string log_line = 1;
    {PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_.log_line_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string model_id = 2;
    {PROTOBUF_FIELD_OFFSET(InferenceRequest, _impl_.model_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\10\10\0\0\0\0\0"
    "inference.InferenceRequest"
    "log_line"
    "model_id"
  }},
};
PROTOBUF_NOINLINE void InferenceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.InferenceRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.log_line_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.model_id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL InferenceRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const InferenceRequest& this_ = static_cast<const InferenceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL InferenceRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const InferenceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:inference.InferenceRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string log_line = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_log_line().empty()) {
      const ::std::string& _s = this_._internal_log_line();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "inference.InferenceRequest.log_line");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string model_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_model_id().empty()) {
      const ::std::string& _s = this_._internal_model_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "inference.InferenceRequest.model_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.InferenceRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InferenceRequest::ByteSizeLong(const MessageLite& base) {
  const InferenceRequest& this_ = static_cast<const InferenceRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InferenceRequest::ByteSizeLong() const {
  const InferenceRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:inference.InferenceRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string log_line = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_log_line().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_log_line());
      }
    }
    // string model_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_model_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_model_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void InferenceRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<InferenceRequest*>(&to_msg);
  auto& from = static_cast<const InferenceRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.InferenceRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_log_line().empty()) {
        _this->_internal_set_log_line(from._internal_log_line());
      } else {
        if (_this->_impl_.log_line_.IsDefault()) {
          _this->_internal_set_log_line("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_model_id().empty()) {
        _this->_internal_set_model_id(from._internal_model_id());
      } else {
        if (_this->_impl_.model_id_.IsDefault()) {
          _this->_internal_set_model_id("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void InferenceRequest::CopyFrom(const InferenceRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:inference.InferenceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InferenceRequest::InternalSwap(InferenceRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_line_, &other->_impl_.log_line_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_id_, &other->_impl_.model_id_, arena);
}

::google::protobuf::Metadata InferenceRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InferenceResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<InferenceResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_._has_bits_);
};

InferenceResponse::InferenceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InferenceResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:inference.InferenceResponse)
}
PROTOBUF_NDEBUG_INLINE InferenceResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::inference::InferenceResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        embedding_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::inference::InferenceResponse,
            PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.embedding_)>()
        , from.embedding_}
        #else
        embedding_ { visibility, arena, from.embedding_ }
        #endif
     {}

InferenceResponse::InferenceResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const InferenceResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InferenceResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InferenceResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_stale_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, is_stale_),
           offsetof(Impl_, z_) -
               offsetof(Impl_, is_stale_) +
               sizeof(Impl_::z_));

  // @@protoc_insertion_point(copy_constructor:inference.InferenceResponse)
}
PROTOBUF_NDEBUG_INLINE InferenceResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        embedding_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::inference::InferenceResponse,
            PROTOBUF_FIELD_OFFSET(::inference::InferenceResponse, _impl_.embedding_)>()
        }
        #else
        embedding_ { visibility, arena }
        #endif
     {}

inline void InferenceResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_stale_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, is_stale_) +
               sizeof(Impl_::z_));
}
InferenceResponse::~InferenceResponse() {
  // @@protoc_insertion_point(destructor:inference.InferenceResponse)
  SharedDtor(*this);
}
inline void InferenceResponse::SharedDtor(MessageLite& self) {
  InferenceResponse& this_ = static_cast<InferenceResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL InferenceResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) InferenceResponse(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto InferenceResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(InferenceResponse),
                                            alignof(InferenceResponse));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto InferenceResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.embedding_) +
          decltype(InferenceResponse::_impl_.embedding_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(InferenceResponse), alignof(InferenceResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&InferenceResponse::PlacementNew_,
                                 sizeof(InferenceResponse),
                                 alignof(InferenceResponse));
  }
}
#endif
constexpr auto InferenceResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_InferenceResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &InferenceResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<InferenceResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &InferenceResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<InferenceResponse>(), &InferenceResponse::ByteSizeLong,
              &InferenceResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_._cached_size_),
          false,
      },
      &InferenceResponse::kDescriptorMethods,
      &descriptor_table_inference_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull InferenceResponse_class_data_ =
        InferenceResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
InferenceResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&InferenceResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(InferenceResponse_class_data_.tc_table);
  return InferenceResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
InferenceResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967234,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    InferenceResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::inference::InferenceResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float embedding = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.embedding_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bool is_stale = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(InferenceResponse, _impl_.is_stale_), 1>(),
     {24, 1, 0,
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.is_stale_)}},
    // float x = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 2, 0,
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.x_)}},
    // float y = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 3, 0,
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.y_)}},
    // float z = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 4, 0,
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.z_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float embedding = 1;
    {PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.embedding_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // bool is_stale = 3;
    {PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.is_stale_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // float x = 4;
    {PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.x_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float y = 5;
    {PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.y_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float z = 6;
    {PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.z_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void InferenceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.InferenceResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.embedding_.Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.is_stale_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.z_) -
        reinterpret_cast<char*>(&_impl_.is_stale_)) + sizeof(_impl_.z_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL InferenceResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const InferenceResponse& this_ = static_cast<const InferenceResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL InferenceResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const InferenceResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:inference.InferenceResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated float embedding = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (this_._internal_embedding_size() > 0) {
      target = stream->WriteFixedPacked(1, this_._internal_embedding(), target);
    }
  }

  // bool is_stale = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_is_stale() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_is_stale(), target);
    }
  }

  // float x = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_x(), target);
    }
  }

  // float y = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          5, this_._internal_y(), target);
    }
  }

  // float z = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          6, this_._internal_z(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.InferenceResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InferenceResponse::ByteSizeLong(const MessageLite& base) {
  const InferenceResponse& this_ = static_cast<const InferenceResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InferenceResponse::ByteSizeLong() const {
  const InferenceResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:inference.InferenceResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated float embedding = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_embedding_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // bool is_stale = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_is_stale() != 0) {
        total_size += 2;
      }
    }
    // float x = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
        total_size += 5;
      }
    }
    // float y = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
        total_size += 5;
      }
    }
    // float z = 6;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void InferenceResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<InferenceResponse*>(&to_msg);
  auto& from = static_cast<const InferenceResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:inference.InferenceResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_embedding()->MergeFrom(from._internal_embedding());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_is_stale() != 0) {
        _this->_impl_.is_stale_ = from._impl_.is_stale_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_z()) != 0) {
        _this->_impl_.z_ = from._impl_.z_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void InferenceResponse::CopyFrom(const InferenceResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:inference.InferenceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InferenceResponse::InternalSwap(InferenceResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.embedding_.InternalSwap(&other->_impl_.embedding_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.z_)
      + sizeof(InferenceResponse::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(InferenceResponse, _impl_.is_stale_)>(
          reinterpret_cast<char*>(&_impl_.is_stale_),
          reinterpret_cast<char*>(&other->_impl_.is_stale_));
}

::google::protobuf::Metadata InferenceResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace inference
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_inference_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
