// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace inference {

static const char* InferenceEngine_method_names[] = {
  "/inference.InferenceEngine/RunInference",
};

std::unique_ptr< InferenceEngine::Stub> InferenceEngine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceEngine::Stub> stub(new InferenceEngine::Stub(channel, options));
  return stub;
}

InferenceEngine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RunInference_(InferenceEngine_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InferenceEngine::Stub::RunInference(::grpc::ClientContext* context, const ::inference::InferenceRequest& request, ::inference::InferenceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inference::InferenceRequest, ::inference::InferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RunInference_, context, request, response);
}

void InferenceEngine::Stub::async::RunInference(::grpc::ClientContext* context, const ::inference::InferenceRequest* request, ::inference::InferenceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inference::InferenceRequest, ::inference::InferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunInference_, context, request, response, std::move(f));
}

void InferenceEngine::Stub::async::RunInference(::grpc::ClientContext* context, const ::inference::InferenceRequest* request, ::inference::InferenceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunInference_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inference::InferenceResponse>* InferenceEngine::Stub::PrepareAsyncRunInferenceRaw(::grpc::ClientContext* context, const ::inference::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inference::InferenceResponse, ::inference::InferenceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RunInference_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inference::InferenceResponse>* InferenceEngine::Stub::AsyncRunInferenceRaw(::grpc::ClientContext* context, const ::inference::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRunInferenceRaw(context, request, cq);
  result->StartCall();
  return result;
}

InferenceEngine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceEngine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceEngine::Service, ::inference::InferenceRequest, ::inference::InferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceEngine::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inference::InferenceRequest* req,
             ::inference::InferenceResponse* resp) {
               return service->RunInference(ctx, req, resp);
             }, this)));
}

InferenceEngine::Service::~Service() {
}

::grpc::Status InferenceEngine::Service::RunInference(::grpc::ServerContext* context, const ::inference::InferenceRequest* request, ::inference::InferenceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inference
#include <grpcpp/ports_undef.inc>

