# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"6\n\x10InferenceRequest\x12\x10\n\x08log_line\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\"8\n\x11InferenceResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x10\n\x08is_stale\x18\x03 \x01(\x08\x32\\\n\x0fInferenceEngine\x12I\n\x0cRunInference\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=84
  _globals['_INFERENCERESPONSE']._serialized_start=86
  _globals['_INFERENCERESPONSE']._serialized_end=142
  _globals['_INFERENCEENGINE']._serialized_start=144
  _globals['_INFERENCEENGINE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
