// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inference.proto
// Protobuf C++ Version: 7.34.1

#ifndef inference_2eproto_2epb_2eh
#define inference_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_inference_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_inference_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_inference_2eproto;
}  // extern "C"
namespace inference {
class InferenceRequest;
struct InferenceRequestDefaultTypeInternal;
extern InferenceRequestDefaultTypeInternal _InferenceRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InferenceRequest_class_data_;
class InferenceResponse;
struct InferenceResponseDefaultTypeInternal;
extern InferenceResponseDefaultTypeInternal _InferenceResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull InferenceResponse_class_data_;
}  // namespace inference
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace inference {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED InferenceResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:inference.InferenceResponse) */ {
 public:
  inline InferenceResponse() : InferenceResponse(nullptr) {}
  ~InferenceResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InferenceResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InferenceResponse));
  }
#endif

  template <typename = void>
  explicit constexpr InferenceResponse(::google::protobuf::internal::ConstantInitialized);

  inline InferenceResponse(const InferenceResponse& from) : InferenceResponse(nullptr, from) {}
  inline InferenceResponse(InferenceResponse&& from) noexcept
      : InferenceResponse(nullptr, ::std::move(from)) {}
  inline InferenceResponse& operator=(const InferenceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferenceResponse& operator=(InferenceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const InferenceResponse& default_instance() {
    return *reinterpret_cast<const InferenceResponse*>(
        &_InferenceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(InferenceResponse& a, InferenceResponse& b) { a.Swap(&b); }
  inline void Swap(InferenceResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferenceResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] InferenceResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InferenceResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InferenceResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InferenceResponse& from) { InferenceResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InferenceResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "inference.InferenceResponse"; }

  explicit InferenceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InferenceResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InferenceResponse& from);
  InferenceResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InferenceResponse&& from) noexcept
      : InferenceResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEmbeddingFieldNumber = 1,
    kIsStaleFieldNumber = 3,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kZFieldNumber = 6,
  };
  // repeated float embedding = 1;
  [[nodiscard]] int embedding_size()
      const;
  private:
  int _internal_embedding_size() const;

  public:
  void clear_embedding() ;
  [[nodiscard]] float embedding(int index) const;
  void set_embedding(int index, float value);
  void add_embedding(float value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<float>& embedding() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_embedding();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_embedding() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_embedding();

  public:
  // bool is_stale = 3;
  void clear_is_stale() ;
  [[nodiscard]] bool is_stale() const;
  void set_is_stale(bool value);

  private:
  bool _internal_is_stale() const;
  void _internal_set_is_stale(bool value);

  public:
  // float x = 4;
  void clear_x() ;
  [[nodiscard]] float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 5;
  void clear_y() ;
  [[nodiscard]] float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 6;
  void clear_z() ;
  [[nodiscard]] float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:inference.InferenceResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InferenceResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> embedding_;
    bool is_stale_;
    float x_;
    float y_;
    float z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InferenceResponse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED InferenceRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:inference.InferenceRequest) */ {
 public:
  inline InferenceRequest() : InferenceRequest(nullptr) {}
  ~InferenceRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InferenceRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InferenceRequest));
  }
#endif

  template <typename = void>
  explicit constexpr InferenceRequest(::google::protobuf::internal::ConstantInitialized);

  inline InferenceRequest(const InferenceRequest& from) : InferenceRequest(nullptr, from) {}
  inline InferenceRequest(InferenceRequest&& from) noexcept
      : InferenceRequest(nullptr, ::std::move(from)) {}
  inline InferenceRequest& operator=(const InferenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferenceRequest& operator=(InferenceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const InferenceRequest& default_instance() {
    return *reinterpret_cast<const InferenceRequest*>(
        &_InferenceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(InferenceRequest& a, InferenceRequest& b) { a.Swap(&b); }
  inline void Swap(InferenceRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferenceRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] InferenceRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InferenceRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InferenceRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InferenceRequest& from) { InferenceRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InferenceRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "inference.InferenceRequest"; }

  explicit InferenceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  InferenceRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InferenceRequest& from);
  InferenceRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, InferenceRequest&& from) noexcept
      : InferenceRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLogLineFieldNumber = 1,
    kModelIdFieldNumber = 2,
  };
  // string log_line = 1;
  void clear_log_line() ;
  [[nodiscard]] const ::std::string& log_line() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_log_line(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_log_line();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_log_line();
  void set_allocated_log_line(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_log_line() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_log_line(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_log_line();

  public:
  // string model_id = 2;
  void clear_model_id() ;
  [[nodiscard]] const ::std::string& model_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_model_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_model_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_model_id();
  void set_allocated_model_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_model_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_model_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_model_id();

  public:
  // @@protoc_insertion_point(class_scope:inference.InferenceRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 51,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const InferenceRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr log_line_;
    ::google::protobuf::internal::ArenaStringPtr model_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_inference_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull InferenceRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// InferenceRequest

// string log_line = 1;
inline void InferenceRequest::clear_log_line() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_line_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& InferenceRequest::log_line() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:inference.InferenceRequest.log_line)
  return _internal_log_line();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InferenceRequest::set_log_line(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.log_line_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:inference.InferenceRequest.log_line)
}
inline ::std::string* PROTOBUF_NONNULL InferenceRequest::mutable_log_line()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_log_line();
  // @@protoc_insertion_point(field_mutable:inference.InferenceRequest.log_line)
  return _s;
}
inline const ::std::string& InferenceRequest::_internal_log_line() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.log_line_.Get();
}
inline void InferenceRequest::_internal_set_log_line(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_line_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InferenceRequest::_internal_mutable_log_line() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.log_line_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InferenceRequest::release_log_line() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:inference.InferenceRequest.log_line)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.log_line_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.log_line_.Set("", GetArena());
  }
  return released;
}
inline void InferenceRequest::set_allocated_log_line(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.log_line_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.log_line_.IsDefault()) {
    _impl_.log_line_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:inference.InferenceRequest.log_line)
}

// string model_id = 2;
inline void InferenceRequest::clear_model_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& InferenceRequest::model_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:inference.InferenceRequest.model_id)
  return _internal_model_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void InferenceRequest::set_model_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.model_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:inference.InferenceRequest.model_id)
}
inline ::std::string* PROTOBUF_NONNULL InferenceRequest::mutable_model_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_model_id();
  // @@protoc_insertion_point(field_mutable:inference.InferenceRequest.model_id)
  return _s;
}
inline const ::std::string& InferenceRequest::_internal_model_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_id_.Get();
}
inline void InferenceRequest::_internal_set_model_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL InferenceRequest::_internal_mutable_model_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.model_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE InferenceRequest::release_model_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:inference.InferenceRequest.model_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.model_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.model_id_.Set("", GetArena());
  }
  return released;
}
inline void InferenceRequest::set_allocated_model_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.model_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_id_.IsDefault()) {
    _impl_.model_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:inference.InferenceRequest.model_id)
}

// -------------------------------------------------------------------

// InferenceResponse

// repeated float embedding = 1;
inline int InferenceResponse::_internal_embedding_size() const {
  return _internal_embedding().size();
}
inline int InferenceResponse::embedding_size() const {
  return _internal_embedding_size();
}
inline void InferenceResponse::clear_embedding() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.embedding_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float InferenceResponse::embedding(int index) const {
  // @@protoc_insertion_point(field_get:inference.InferenceResponse.embedding)
  return _internal_embedding().Get(index);
}
inline void InferenceResponse::set_embedding(int index, float value) {
  _internal_mutable_embedding()->Set(index, value);
  // @@protoc_insertion_point(field_set:inference.InferenceResponse.embedding)
}
inline void InferenceResponse::add_embedding(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_embedding()->InternalAddWithArena(
      internal_visibility(), GetArena(), value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:inference.InferenceResponse.embedding)
}
inline const ::google::protobuf::RepeatedField<float>& InferenceResponse::embedding() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:inference.InferenceResponse.embedding)
  return _internal_embedding();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL InferenceResponse::mutable_embedding()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:inference.InferenceResponse.embedding)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_embedding();
}
inline const ::google::protobuf::RepeatedField<float>&
InferenceResponse::_internal_embedding() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.embedding_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
InferenceResponse::_internal_mutable_embedding() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.embedding_;
}

// bool is_stale = 3;
inline void InferenceResponse::clear_is_stale() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_stale_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool InferenceResponse::is_stale() const {
  // @@protoc_insertion_point(field_get:inference.InferenceResponse.is_stale)
  return _internal_is_stale();
}
inline void InferenceResponse::set_is_stale(bool value) {
  _internal_set_is_stale(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:inference.InferenceResponse.is_stale)
}
inline bool InferenceResponse::_internal_is_stale() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_stale_;
}
inline void InferenceResponse::_internal_set_is_stale(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_stale_ = value;
}

// float x = 4;
inline void InferenceResponse::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float InferenceResponse::x() const {
  // @@protoc_insertion_point(field_get:inference.InferenceResponse.x)
  return _internal_x();
}
inline void InferenceResponse::set_x(float value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:inference.InferenceResponse.x)
}
inline float InferenceResponse::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void InferenceResponse::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 5;
inline void InferenceResponse::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline float InferenceResponse::y() const {
  // @@protoc_insertion_point(field_get:inference.InferenceResponse.y)
  return _internal_y();
}
inline void InferenceResponse::set_y(float value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:inference.InferenceResponse.y)
}
inline float InferenceResponse::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void InferenceResponse::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 6;
inline void InferenceResponse::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline float InferenceResponse::z() const {
  // @@protoc_insertion_point(field_get:inference.InferenceResponse.z)
  return _internal_z();
}
inline void InferenceResponse::set_z(float value) {
  _internal_set_z(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:inference.InferenceResponse.z)
}
inline float InferenceResponse::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void InferenceResponse::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace inference


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // inference_2eproto_2epb_2eh
