// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: advisor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What the Go Orchestrator sends to the C++ Engine
type DiagnosisRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventType       string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ServiceName     string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ErrorContent    string                 `protobuf:"bytes,3,opt,name=error_content,json=errorContent,proto3" json:"error_content,omitempty"`
	EstimatedImpact string                 `protobuf:"bytes,4,opt,name=estimated_impact,json=estimatedImpact,proto3" json:"estimated_impact,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagnosisRequest) Reset() {
	*x = DiagnosisRequest{}
	mi := &file_advisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisRequest) ProtoMessage() {}

func (x *DiagnosisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisRequest.ProtoReflect.Descriptor instead.
func (*DiagnosisRequest) Descriptor() ([]byte, []int) {
	return file_advisor_proto_rawDescGZIP(), []int{0}
}

func (x *DiagnosisRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DiagnosisRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiagnosisRequest) GetErrorContent() string {
	if x != nil {
		return x.ErrorContent
	}
	return ""
}

func (x *DiagnosisRequest) GetEstimatedImpact() string {
	if x != nil {
		return x.EstimatedImpact
	}
	return ""
}

type DiagnosisResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Diagnosis       string                 `protobuf:"bytes,1,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // e.g., 0.95
	SuggestedAction string                 `protobuf:"bytes,3,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagnosisResponse) Reset() {
	*x = DiagnosisResponse{}
	mi := &file_advisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisResponse) ProtoMessage() {}

func (x *DiagnosisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisResponse.ProtoReflect.Descriptor instead.
func (*DiagnosisResponse) Descriptor() ([]byte, []int) {
	return file_advisor_proto_rawDescGZIP(), []int{1}
}

func (x *DiagnosisResponse) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *DiagnosisResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *DiagnosisResponse) GetSuggestedAction() string {
	if x != nil {
		return x.SuggestedAction
	}
	return ""
}

var File_advisor_proto protoreflect.FileDescriptor

const file_advisor_proto_rawDesc = "" +
	"\n" +
	"\radvisor.proto\x12\aadvisor\"\xa4\x01\n" +
	"\x10DiagnosisRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12#\n" +
	"\rerror_content\x18\x03 \x01(\tR\ferrorContent\x12)\n" +
	"\x10estimated_impact\x18\x04 \x01(\tR\x0festimatedImpact\"\x87\x01\n" +
	"\x11DiagnosisResponse\x12\x1c\n" +
	"\tdiagnosis\x18\x01 \x01(\tR\tdiagnosis\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12)\n" +
	"\x10suggested_action\x18\x03 \x01(\tR\x0fsuggestedAction2S\n" +
	"\n" +
	"SREAdvisor\x12E\n" +
	"\fGetDiagnosis\x12\x19.advisor.DiagnosisRequest\x1a\x1a.advisor.DiagnosisResponseB\tZ\a./protob\x06proto3"

var (
	file_advisor_proto_rawDescOnce sync.Once
	file_advisor_proto_rawDescData []byte
)

func file_advisor_proto_rawDescGZIP() []byte {
	file_advisor_proto_rawDescOnce.Do(func() {
		file_advisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advisor_proto_rawDesc), len(file_advisor_proto_rawDesc)))
	})
	return file_advisor_proto_rawDescData
}

var file_advisor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_advisor_proto_goTypes = []any{
	(*DiagnosisRequest)(nil),  // 0: advisor.DiagnosisRequest
	(*DiagnosisResponse)(nil), // 1: advisor.DiagnosisResponse
}
var file_advisor_proto_depIdxs = []int32{
	0, // 0: advisor.SREAdvisor.GetDiagnosis:input_type -> advisor.DiagnosisRequest
	1, // 1: advisor.SREAdvisor.GetDiagnosis:output_type -> advisor.DiagnosisResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_advisor_proto_init() }
func file_advisor_proto_init() {
	if File_advisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advisor_proto_rawDesc), len(file_advisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advisor_proto_goTypes,
		DependencyIndexes: file_advisor_proto_depIdxs,
		MessageInfos:      file_advisor_proto_msgTypes,
	}.Build()
	File_advisor_proto = out.File
	file_advisor_proto_goTypes = nil
	file_advisor_proto_depIdxs = nil
}
