// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: advisor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SREAdvisor_GetDiagnosis_FullMethodName = "/advisor.SREAdvisor/GetDiagnosis"
)

// SREAdvisorClient is the client API for SREAdvisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The "Brain" Service
type SREAdvisorClient interface {
	// The Orchestrator calls this to get a diagnosis
	GetDiagnosis(ctx context.Context, in *DiagnosisRequest, opts ...grpc.CallOption) (*DiagnosisResponse, error)
}

type sREAdvisorClient struct {
	cc grpc.ClientConnInterface
}

func NewSREAdvisorClient(cc grpc.ClientConnInterface) SREAdvisorClient {
	return &sREAdvisorClient{cc}
}

func (c *sREAdvisorClient) GetDiagnosis(ctx context.Context, in *DiagnosisRequest, opts ...grpc.CallOption) (*DiagnosisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosisResponse)
	err := c.cc.Invoke(ctx, SREAdvisor_GetDiagnosis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SREAdvisorServer is the server API for SREAdvisor service.
// All implementations must embed UnimplementedSREAdvisorServer
// for forward compatibility.
//
// The "Brain" Service
type SREAdvisorServer interface {
	// The Orchestrator calls this to get a diagnosis
	GetDiagnosis(context.Context, *DiagnosisRequest) (*DiagnosisResponse, error)
	mustEmbedUnimplementedSREAdvisorServer()
}

// UnimplementedSREAdvisorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSREAdvisorServer struct{}

func (UnimplementedSREAdvisorServer) GetDiagnosis(context.Context, *DiagnosisRequest) (*DiagnosisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiagnosis not implemented")
}
func (UnimplementedSREAdvisorServer) mustEmbedUnimplementedSREAdvisorServer() {}
func (UnimplementedSREAdvisorServer) testEmbeddedByValue()                    {}

// UnsafeSREAdvisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SREAdvisorServer will
// result in compilation errors.
type UnsafeSREAdvisorServer interface {
	mustEmbedUnimplementedSREAdvisorServer()
}

func RegisterSREAdvisorServer(s grpc.ServiceRegistrar, srv SREAdvisorServer) {
	// If the following call panics, it indicates UnimplementedSREAdvisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SREAdvisor_ServiceDesc, srv)
}

func _SREAdvisor_GetDiagnosis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SREAdvisorServer).GetDiagnosis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SREAdvisor_GetDiagnosis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SREAdvisorServer).GetDiagnosis(ctx, req.(*DiagnosisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SREAdvisor_ServiceDesc is the grpc.ServiceDesc for SREAdvisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SREAdvisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "advisor.SREAdvisor",
	HandlerType: (*SREAdvisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiagnosis",
			Handler:    _SREAdvisor_GetDiagnosis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "advisor.proto",
}
