// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: inference.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceEngine_RunInference_FullMethodName = "/inference.InferenceEngine/RunInference"
)

// InferenceEngineClient is the client API for InferenceEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceEngineClient interface {
	RunInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
}

type inferenceEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceEngineClient(cc grpc.ClientConnInterface) InferenceEngineClient {
	return &inferenceEngineClient{cc}
}

func (c *inferenceEngineClient) RunInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_RunInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceEngineServer is the server API for InferenceEngine service.
// All implementations must embed UnimplementedInferenceEngineServer
// for forward compatibility.
type InferenceEngineServer interface {
	RunInference(context.Context, *InferenceRequest) (*InferenceResponse, error)
	mustEmbedUnimplementedInferenceEngineServer()
}

// UnimplementedInferenceEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceEngineServer struct{}

func (UnimplementedInferenceEngineServer) RunInference(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunInference not implemented")
}
func (UnimplementedInferenceEngineServer) mustEmbedUnimplementedInferenceEngineServer() {}
func (UnimplementedInferenceEngineServer) testEmbeddedByValue()                         {}

// UnsafeInferenceEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceEngineServer will
// result in compilation errors.
type UnsafeInferenceEngineServer interface {
	mustEmbedUnimplementedInferenceEngineServer()
}

func RegisterInferenceEngineServer(s grpc.ServiceRegistrar, srv InferenceEngineServer) {
	// If the following call panics, it indicates UnimplementedInferenceEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceEngine_ServiceDesc, srv)
}

func _InferenceEngine_RunInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).RunInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_RunInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).RunInference(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceEngine_ServiceDesc is the grpc.ServiceDesc for InferenceEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.InferenceEngine",
	HandlerType: (*InferenceEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunInference",
			Handler:    _InferenceEngine_RunInference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference.proto",
}
